<header>
    <nav class="navbar">
        <div class="branding">
            <h1>AB IT Limited</h1>
        </div>
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="jobs.php">Jobs</a></li>
            <li><a href="apply.php">Apply</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="manage.php">Manage</a></li>
            <li><a href="enhancements.php">En 1</a></li>
            <li><a href="enhancements2.php">En  2</a></li>
            <li><a href="phpenhancements.php">En PHP</a></li>
        </ul>
    </nav>
</header>